server:
  port: 9001
spring:
  application:
    name: mytensupare_base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.8.44:3306/tensquare_base?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true

