server:
  port: 9003
spring:
  application:
    name: mytenspuare_qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.8.44:3306/tensquare_recruit?characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    show-sql: true

